# This is a basic workflow to help you get started with Actions

name: Build OpenCore For GA-Z97-D3H

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  REPO_URL: https://github.com/acidanthera/OcBinaryData.git

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macOS-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Get OcBinaryData
        run: |
          git clone --depth 1 $REPO_URL OcBinaryData

      # Runs commands using the runners shell
      - name: Get Latest OC
        id: getoc
        run: |
          echo "FILE_DATE=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
          cd $GITHUB_WORKSPACE/Tools/
          chmod +x get_latest_kexts.sh
          chmod +x get_latest_oc.sh
          sh get_latest_oc.sh || true
          cd EFI
          echo "EFI=$PWD" >> $GITHUB_ENV
          echo "::set-output name=status::success"
      
      - name: Upload EFI directory
        uses: actions/upload-artifact@main
        if: steps.getoc.outputs.status == 'success' && !cancelled()
        with:
          name: EFI_${{ env.OC_VER }}_${{ env.FILE_DATE }}
          path: ${{ env.EFI }}
        
      
